### ISSUE TITLE
Converted photo is rotated - Incorrect EXIF orientation

### ISSUE THREAD

**Issue by pawelkierklo** [greenrivers/grav-plugin-webp#7] opened 2022-12-09 17:15 UTC
Simply problem, GRAV haven't rotation function.

**Comment by MajorKuprich** [comment] 2022-12-25 19:50
Hello @pawelkierklo,

I didn't manage to reproduce this issue.
Could You send me the image with this error?

Regards

**Comment by pawelkierklo** [comment] 2022-12-26 11:33
Example photo with EXIF rotate [JPG](https://buduj.elk.pl/user/pages/01.witamy/_intro/20220924_145958.jpg) and result [WEBP](https://buduj.elk.pl/user/webp/user/pages/01.witamy/_intro/20220924_145958.webp)

**Comment by MajorKuprich** [comment] 2022-12-26 19:50
Thank You @pawelkierklo,

Fixed in new [release](https://github.com/greenrivers/grav-plugin-webp/releases/tag/1.4.2).
Related commit: https://github.com/greenrivers/grav-plugin-webp/commit/b61ec74b4aedcd7014ed0b85d5aac38abff0cc70.

**Comment by MajorKuprich** [comment] 2023-02-02 20:55
It has been over month since last activity in this topic, so I close this issue.
Reopen or create new ticket if You need more explanations, please. :)

**Closed as completed by MajorKuprich** 2023-02-02 20:55 UTC
Labels: bug
