### ISSUE TITLE
Double slash on rendered image URL

### ISSUE THREAD

**Issue by Funkwarrior** [greenrivers/grav-plugin-webp#5] opened 2021-09-24 08:40 UTC
Hi,
I have an a double slash path on my rendered image url
`user/webp//user/themes/my-theme/images/logo.webp`

The problem seems to be on getWebpPath and getWebpDir functions in Image.php Helper and in Converter.php Helper where they are used.

The images are displayed correctly but the double slash is not a good practice for SEO.

Hope this will be fixed soon.

(Also there is a bunch of error exceptions in the plugin admin panel using a debugger..)

**Comment by MajorKuprich** [comment] 2021-09-30 19:34
Hello @Funkwarrior,

I cannot reproduce Your error, tested on PHP 7.4 & Grav 1.7.22.

Could You give me more info:
- PHP version
- Grav version
- output from logs/grav.log file
- screen with exceptions in admin plugin panel
- web browser on which You discover double slash

Is already this issue solved from Your side and that's why You closed this topic?

**Comment by MajorKuprich** [comment] 2021-12-14 16:04
It has been almost 3 months since last activity in this topic, so I close this issue.
Reopen or create new ticket if You need more explanations, please. :)

**Closed as completed by MajorKuprich** 2021-12-14 16:04 UTC
