### ISSUE TITLE
Plugin don't convert all images bug

### ISSUE THREAD

**Issue by danielkoptak** [greenrivers/grav-plugin-webp#6] opened 2022-10-05 18:19 UTC
When I run convert, it can handle most of the images up to the last 605 images (I have about 3600 images). In request is displayed converted_images:0  and so the whole process is looped
![image](https://user-images.githubusercontent.com/79636201/194133034-2b7c452b-373e-4dca-902b-bd809c9e546d.png)

**Comment by MajorKuprich** [comment] 2022-10-11 20:39
Hi @danielkoptak,

Unfortunately I can't reproduce this error.
I've tested with 3500 images in my environment - most of them converted to webp format.

Could You give me more info about:
- PHP version
- PHP settings (**max_execution_time**, **max_input_time**, **memory_limit**)
- images format which You want to convert (remember that extension working with **jpg**, **jpeg** and **png**)

In case any problems with large amount of images to processing You can refresh page and click on the convert button again.

Regards

**Comment by danielkoptak** [comment] 2022-10-17 17:11
Grav v1.7.37.1
PHP Version 7.4.32
max_execution_time 90
max_input_time 60
memory_limit 2048M

if i refresh the page then i see: Converted 0/605 image - but nothing happens. It looks like one of the images is causing problems when converting. Is there a way to find out the name of the image that is being converted? (console output...)

**Comment by MajorKuprich** [comment] 2022-10-18 18:22
Hello @danielkoptak,

PHP config looks fine.

You can preview the image data by adding code fragment at the beginning of the convert function, before this line: https://github.com/greenrivers/grav-plugin-webp/blob/master/classes/Helper/Converter.php#L34.

1. View image data & stop conversion - preview available from browser console.
```php
        var_dump($image);
        exit();
```
When You start conversion, the process stops at the first image - then You can preview its data.
It should be the image that blocks the conversion of the other files.

E.g. for **Chrome** &rarr; **Network** tab, **convert** request:

![chrome](https://i.imgur.com/oHYuLlM.png)

2. Logging for each image.
```php
        $log = \Grav\Common\Grav::instance()['log'];
        $log->info('Image: ' . json_encode($image));
```
Logs available in _logs/grav.log_

Example log:
```
[2022-10-18 17:55:56] grav.INFO: Image: {"extension":"jpg","pathname":"user\/themes\/greenrivers\/images\/desktop_home.jpg","pathinfo":{"pathname":"user\/themes\/greenrivers\/images"},"filenamewithoutextension":"desktop_home"} [] []
```

Please let me know if you have any further questions.

**Comment by MajorKuprich** [comment] 2022-12-20 10:24
It has been over 2 months since last activity in this topic, so I close this issue.
Reopen or create new ticket if You need more explanations, please. :)

**Closed as completed by MajorKuprich** 2022-12-20 10:24 UTC
Labels: bug
